# Railway Configuration - Minimal Backend Deployment
[build]

[deploy]
  startCommand = "cd backend && npm install && npm start"

[env]
  MONGODB_URI = "your_mongodb_connection_string"
  JWT_KEY = "your_jwt_secret_key"  
  GOOGLE_MAPS_API_KEY = "your_google_maps_api_key"
  PORT = "5000"
  NODE_ENV = "production"
