# Railway Configuration - Backend Only
# This ensures Railway only builds and deploys the backend

[build]
  command = "cd backend && npm ci --only=production"

[deploy]
  startCommand = "cd backend && npm start"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[env]
  MONGODB_URI = "your_mongodb_connection_string"
  JWT_KEY = "your_jwt_secret_key"
  GOOGLE_MAPS_API_KEY = "your_google_maps_api_key"
  PORT = "5000"
  NODE_ENV = "production"

[healthcheck]
  path = "/api/users"
  timeout = 30
