# Railway Configuration - Backend Only Deployment
[build]
  builder = "NIXPACKS"
  buildCommand = "npm install"

[deploy]
  startCommand = "node backend/app.js"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[env]
  # These will be set in Railway dashboard
  MONGODB_URI = "${{MONGODB_URI}}"
  JWT_KEY = "${{JWT_KEY}}"  
  GOOGLE_MAPS_API_KEY = "${{GOOGLE_MAPS_API_KEY}}"
  PORT = "${{PORT}}"
  NODE_ENV = "production"
