# Railway Configuration - Backend Only Deployment
[build]

[deploy]
  startCommand = "cd backend && npm install && npm start"

[env]
  # These will be set in Railway dashboard
  MONGODB_URI = "${{MONGODB_URI}}"
  JWT_KEY = "${{JWT_KEY}}"  
  GOOGLE_MAPS_API_KEY = "${{GOOGLE_MAPS_API_KEY}}"
  PORT = "${{PORT}}"
  NODE_ENV = "production"
