# Railway Configuration
# This file helps Railway understand your project structure

[build]
  command = "cd backend && npm install"

[deploy]
  startCommand = "cd backend && npm start"

[env]
  MONGODB_URI = "your_mongodb_connection_string"
  JWT_KEY = "your_jwt_secret_key"
  GOOGLE_MAPS_API_KEY = "your_google_maps_api_key"
  PORT = "5000"
  NODE_ENV = "production"

[healthcheck]
  path = "/api/users"
  timeout = 30
